#!/bin/sh
set -e

# Replace environment variables in the Nginx config
envsubst '${OPNFORM_UI_HOSTNAME} ${OPNFORM_API_HOSTNAME}' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf.tmp
mv /etc/nginx/conf.d/default.conf.tmp /etc/nginx/conf.d/default.conf

# Execute the CMD
exec "$@"
